### ISSUE TITLE
Transparent background not working

### ISSUE THREAD

**Issue by lfschenone** [graphp/graphviz#11]
After a long dive into the source code, I found the way to set a background for my graph, but although the colored backgrounds work fine, the transparent background doesn't seem to. The following code outputs a basic graph with a red background:

	$Graph = new Fhaculty\Graph\Graph;
	$Graph->setAttribute( 'graphviz.graph.bgcolor', 'red' );

	$Vertex1 = $Graph->createVertex();
	$Vertex2 = $Graph->createVertex();
	$Vertex1->createEdge( $Vertex2 );

	$GraphViz = new Graphp\GraphViz\GraphViz;
	$data = $GraphViz->createImageData( $Graph );
	$image = imagecreatefromstring( $data );
	header( 'Content-Type: image/png' );
	imagepng( $image );

According to the [official Graphviz documentation](http://www.graphviz.org/doc/info/attrs.html#d:bgcolor), the bgcolor attribute should also allow a 'transparent' value. But if I set bgcolor to 'transparent' I get a black background, just like the one I get when I set it to 'alksmdlkamsdklmadlmas' or any other invalid value.

**Comment by clue** [comment]
Thanks for posting this here @lfschenone!

> although the colored backgrounds work fine, the transparent background doesn't seem to

Thanks for the provided test script. I think this (again) boils down to a lack of documentation :)

The `transparent` key does indeed work and GraphViz does print a graph image with a transparent background.

However, PHP's `imagecreatefromstring()` function ignores this alpha channel information and hence defaults to a black background instead. One way to make this work is to explicitly pass the alpha information to PHP.

Afaict however, a call to this function is not needed anyway. Your use case can probably be simplified like this:

```php
$GraphViz = new Graphp\GraphViz\GraphViz;
header( 'Content-Type: image/png' );
echo $GraphViz->createImageData( $Graph );
```
