### ISSUE TITLE
Documentation: How to add properties to graph

### ISSUE THREAD

**Issue by masipila** [graphp/graphviz#16]
Hi,

I need to change the rankdir of the graph from the default TB (top-to-bottom) to LR (left-right) but I haven't figured out how to add attributes to the graph itself.

The output that I'm looking for is this:
`digraph G {
graph [rankdir="LR"] 
 "Hello"
 "World"
 "Hello"->"World"
}
`
The example on the readme shows how to add attributes to the elements of the graph but not how to add them to the graph itself. The following didn't work:
` $graph = new Graph();
$graph->setAttribute('graphviz.rankdir', 'LR');
`
Cheers,
Markus

**Comment by masipila** [comment]
Read the source, Luke :)

`    $graph = new Graph();
    $graph->setAttribute('graphviz.graph.rankdir', 'LR');
`

**Comment by clue** [comment]
Thanks for posting the answer to your own question! :)

I'll make sure this gets added to the readme once we tackle #2 :+1:
