### ISSUE TITLE
xdg-open silently fails

### ISSUE THREAD

**Issue by lrkwz** [graphp/graphviz#21]
I'm using graphwiz though [docker-compose-viz](https://github.com/pmsipilot/docker-compose-viz) but when run to display on screen the command xdg-open silently fails.

Supposed you have a docker-compose.yml in the current dir the command line used is 

    docker pull pmsipilot/docker-compose-viz
    docker run --rm \
        -it \
        -v $(pwd):/input/ \
        -u 0 \
        pmsipilot/docker-compose-viz \
        render --output-format display

My default image viewer is eog (gnome image viewer)

    $ uname -a
    Linux lrkwz-Precision-SSD-M4500 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.3 LTS
    Release:	16.04
    Codename:	xenial
    $ gnome-shell --version
    GNOME Shell 3.18.5
    $ xdg-open --version
    xdg-open 1.1.0 rc3
    $ eog --version
    GNOME Image Viewer 3.18.2

See https://github.com/pmsipilot/docker-compose-viz/issues/27

**Comment by clue** [comment]
Thank you for reporting!

Can you try running `xdg-open image.svg` manually and see if this reports any errors?

The current API used in this project is kind of awkward and will be reworked as per #14. Once this is in place, it should be far more reasonable to handle this situation and maybe throw an exception etc.

**Comment by lrkwz** [comment]
You are welcome:

    $ xdg-open docker-compose.png
    Gtk-Message: Failed to load module "unity-gtk-module"
    Gtk-Message: Failed to load module "unity-gtk-module"

**Comment by clue** [comment]
I'm not sure I follow, your original report suggests that this library does not open an image and does not report an error, right? Here's a gist of what this library does:

```
$ php -r 'exec("xdg-open docker-compose.png >/dev/null>/dev/null");'
```

**Comment by lrkwz** [comment]
Right.
But your gist works without errors.
So it must be something related to the file being opened (permissions? `dockerd` runs under `root` permissions)

**Comment by lrkwz** [comment]
We are catching it! Yes the command is run inside a docker cotainer

    docker run --rm \
        -it \
        -v $(pwd):/input/ \
        -u 0 \
        pmsipilot/docker-compose-viz \
        php -r 'exec("xdg-open docker-compose.png >/dev/null>/dev/null");'
    sh: xdg-open: not found

@jubianchi can you fix the container?

**Comment by jubianchi** [comment]
thanks @clue and @lrkwz for finding what the real issue was.

I’m going to add the missing cdg-open inthe container.
