### ISSUE TITLE
Setting bgcolor attribute not possible

### ISSUE THREAD

**Issue by flaushi** [graphp/graphviz#22]
Hi,
I am quite happy with the simple interface of this lib. However, when trying to change my outputs background color, I run into problems:
```
$g = new Graph();
        $v = $dc->buildGraph($g);
        $graphviz = new GraphViz();
        $graphviz->setFormat('svg');
        $g->setAttribute('graphviz.bgcolor', 'green');
        var_dump ($graphviz->createScript($g));
```
gives:
```
digraph G {   0 [label="/"]   1 [label="erloes21" color="red"]   2 [label="erloes2gesamt" color="red"]   0 -> 1   0 -> 2 }  [] []
```
and the output has white background.

**Comment by clue** [comment]
@flaushi Very good question! All graphviz graph attributes have to be added like this:

```php
$graph = new Graph();
$graph->setAttribute('graphviz.graph.bgcolor', 'green');
```

I'll make sure this gets added to the readme once we tackle #2 +1
