### ISSUE TITLE
x64 build

### ISSUE THREAD

**Issue by refaelsh** [graphp/graphviz#29]
Hi all,

May I please suggest a build for Windows 10 x64?
I tried doing it myself, and it appears to be that many dependencies are missing.
For example: `\graphviz\windows\dependencies\libraries\x64\lib\xml2.lib`.

Thanks. Refael.

**Comment by clue** [comment]
Hey @refaelsh, welcome to GraPHP!

This project only *uses* Graphviz, so you're required to manually install it. Once you have a suitable version installed, this project will run the Graphviz executable (dot).

I'm not aware if any pre-built binary for 64 bit Windows exists, you may have to ask your favorite search engine (https://stackoverflow.com/questions/50644715/how-to-install-the-64-bit-version-for-windows-10-of-graphviz-2-38).

I hope this helps :+1:

**Comment by refaelsh** [comment]
Oops... Terribly sorry for the bother. My mistake.
