### ISSUE TITLE
Add an option to define the graph ID in dot script

### ISSUE THREAD

**Issue by clue** [graphp/graphviz#3]
> When generating a Graph its name always is 'G' (in svg output it's the title sometimes showed as a web browser tooltip)

From clue/graph#90. Originally reported by @clemens-tolboom.

**Comment by rhelms** [comment]
I'd like to do something to support this, and the workaround from the linked issue doesn't appear to work.

My suggestion would be to allow setting an id attribute on the `Fhaculty\Graph\Graph`, which would be used in the graph statement in `Graphp\GraphViz\GraphViz`.

`$graph->setAttribute('graphviz.id', 'My Graph Title');` would result in `graph 'My Graph Title' {`, which should flow through to the SVG and resulting tooltip.

If not set, we could still default to G. And some extra testing can be done to make sure that an empty string works, even if `''` needs to become `' '`.

**Comment by rhelms** [comment]
I've just done some local code to see how it goes, and looking at the GraphViz doco, it might be better to set an attribute called `graphviz.name` to set the name of the graph.

I'll submit a pull request for this shortly.
