### ISSUE TITLE
Edge direction between ports is always "none"

### ISSUE THREAD

**Issue by hgraca** [graphp/graphviz#30]
Hi,

First let me tell u, congratz on this great wrapper you've built here!

Now, I've found that the edge direction between ports in the same node is always "none".

**TL;DR; the problems are:** 
1. The edge `dir` is always set to `none` if it's between ports of the same node;
2. We are not allowed to set `$edge->setAttribute('graphviz.dir', 'forward');`.

**Here's how to replicate this:**

```php
use Graphp\GraphViz\GraphViz;

set_time_limit(0);

require __DIR__ . '/vendor/autoload.php';

$graph = new Fhaculty\Graph\Graph();

$a = $graph->createVertex();
$a->setAttribute('graphviz.shape', 'Mrecord');
$a->setAttribute(
    'graphviz.label',
    GraphViz::raw('"<f0> left |<middle> middle |<f2> right"')
);

$b = $graph->createVertex();
$b->setAttribute('graphviz.shape', 'Mrecord');
$b->setAttribute(
    'graphviz.label',
    GraphViz::raw('"<f0> left |<f1> middle |<right> right"')
);

// a:middle -> b:right
$edge = $a->createEdgeTo($b);
$edge->setAttribute('graphviz.tailport', 'middle');
$edge->setAttribute('graphviz.headport', 'right');

// a:left -> a:right
$edge = $a->createEdgeTo($a);
$edge->setAttribute('graphviz.tailport', 'f0');
$edge->setAttribute('graphviz.headport', 'f2');
 // adding this yielded the EXACT same result:
$edge->setAttribute('graphviz.dir', 'forward');

file_put_contents(
    'graph.no-vcs.dot',
    (new GraphViz())->createScript($graph)
);
file_put_contents(
    'graph.no-vcs.svg',
    (new GraphViz())->setFormat('svg')->createImageData($graph)
);
```

this originates the following DOT:
```dot
digraph G {
  0 [shape="Mrecord" label="<f0> left |<middle> middle |<f2> right"]
  1 [shape="Mrecord" label="<f0> left |<f1> middle |<right> right"]
  0 -> 1 [tailport="middle" headport="right"]
  0 -> 0 [tailport="f0" headport="f2" dir="none"]
}
```
and the following image:
![graph no-vcs](https://user-images.githubusercontent.com/1809002/50355706-81cca480-0547-11e9-98e8-9057742ccf3e.jpg)

However, if we change the DOT to:
```dot
digraph G {
  0 [shape="Mrecord" label="<f0> left |<middle> middle |<f2> right"]
  1 [shape="Mrecord" label="<f0> left |<f1> middle |<right> right"]
  0 -> 1 [tailport="middle" headport="right"]
  // removed ' dir="none"', but adding ' dir="forward"' also works:
  0 -> 0 [tailport="f0" headport="f2"]
}
```
and run `dot -T jpg ./graph.no-vcs.dot -o ./graph.no-vcs.jpg` we get this image: 
![graph ok no-vcs](https://user-images.githubusercontent.com/1809002/50355905-0cad9f00-0548-11e9-802a-681f23f2efd2.jpg)

**Comment by clue** [comment]
@hgraca Thanks for this excellent issue description and your patience! What you're describing is indeed a bug in this library, so I've just filed #37 to fix rendering directed edges as expected.
