### ISSUE TITLE
Help wanted: obtain the minimal path between nodes

### ISSUE THREAD

**Issue by tematres** [graphp/graphviz#33]
Hi, i'm ver new in this matter (and my english is bad :( ). I want to obtain the minimal path average between a list of nodes. The data are a list of nodes like this:
1,2
2,4
4,1
1,5
5,1
2,1

it is possible? Thank you in advance!

**Comment by clue** [comment]
Hi @tematres, welcome to @GraPHP! :+1: 

It sounds like you're looking for graph algorithms instead of graph drawing. Make sure to check out https://github.com/graphp/algorithms which provides a number of algorithms for finding "shortest paths".

I hope this helps :+1:
