### ISSUE TITLE
Use drupol/launcher

### ISSUE THREAD

**Issue by drupol** [graphp/graphviz#34]
Hi,

I just created a new PHP package: [drupol/launcher](https://github.com/drupol/launcher).

Basically this is a very basic helper that will open any resource that are passed as parameter with the default application of your operating system.

Using this package will remove a bunch of code from [GraphViz.php](https://github.com/graphp/graphviz/blob/master/src/GraphViz.php).

**Comment by clue** [comment]
Hi @drupol, thanks for bringing this to our attention!

I've identified ~10 lines of code that deal with process execution and could potentially be replaced by an external implementation. The amount of code appears reasonable to me and the benefit of using an external dependency is unclear to me at the moment, so in this case I would rather avoid adding an external dependency with its dependency tree.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this persists and we can reopen this :+1:

**Comment by drupol** [comment]
Sure no problem :-) I was just proposing :)
