### ISSUE TITLE
Add possibility to set attributes like "rankdir" and "splines"

### ISSUE THREAD

**Issue by Sebobo** [graphp/graphviz#35]
Currrently it doesn't seem to be possible to set these properties to influence the rendering of the graph.

It would be great to have a `setAttribute` or similar for this on the GraphViz instance.

**Comment by Sebobo** [comment]
Ah found `$graph->setAttribute('graphviz.graph.rankdir', 'LR');` nvm :)

**Comment by clue** [comment]
@Sebobo Glad you've found out already and thanks for sharing your findings :+1:
