### ISSUE TITLE
Allow alphanumerical group ids

### ISSUE THREAD

**Issue by Sebobo** [graphp/graphviz#36]
Currently `setGroup` requires an integer, which will be set as label of the resulting cluster.
But it's more helpful to have alphanumerical cluster names at the end.

Therefore I currently do a string replace on the unique integer id but it would be nice to just set the group id as string.

**Comment by clue** [comment]
@Sebobo Thanks for your input, I think you're raising a good point. There's currently some discussion to remove this whole feature in the underlying library, perhaps you can join the discussion in https://github.com/graphp/graph/pull/168? :+1:
