### ISSUE TITLE
Consider adding HTML attributes

### ISSUE THREAD

**Issue by clue** [graphp/graphviz#4]
> Originally suggested by @clemens-tolboom in https://github.com/clue/graph/pull/96

**Comment by paulovitorbal** [comment]
I can do this, please let me know if you want my help.

**Comment by clue** [comment]
@paulovitorbal Thank you for picking this up! I've just merged #26 which adds documentation for the existing behavior and also for HTML-like labels. I believe this to resolve this for now :shipit: :tada: 

This issue was originally filed to suggest adding additional HTML attributes when embedding a generated image into an HTML document. I have to plans to work on this any time soon and don't see this ticket gaining traction any time soon. 

I'd like to get the next release out and believe this has been answered already, so I'm closing this for now. :shipit:

**Comment by paulovitorbal** [comment]
Nice @clue! I am using this package and if I see something else that I can do. I will open a new PR. You did a really nice work here bro!
