### ISSUE TITLE
Wrong class call in samples

### ISSUE THREAD

**Issue by migmam** [graphp/graphviz#45]
In all the samples the first line is

$graph = new Graph\Graph\Graph();

This is throwing error Class not found.

Shouldn't it be $graph = new Fhaculty\Graph\Graph();  ?

**Comment by clue** [comment]
Hi @migmam, welcome to GraPHP! :wave:

It looks like your referring to the documentation of the current `master` branch which will be released as `v1.0.0` not too far in the future – while you're watching the source code of the `v0.2.x` release branch.

Please refer to the documentation that comes with your installed version or wait for the `v1.0.0` release which will come with a much better architecture and documentation. In the meantime, you can also install from the `master` branch to get the latest development version :+1:
