### ISSUE TITLE
support MacOS Big Sur

### ISSUE THREAD

**Issue by smcoder** [graphp/graphviz#47]
What time is expected to support the new mac system（macos big sur)

**Comment by clue** [comment]
@smcoder This library should be supported on all common platforms.

What makes you think it's not? Are you seeing any problems?

**Comment by smcoder** [comment]
Sorry, I found the problem no longer exists

**Comment by clue** [comment]
Thanks for reporting back this seems to be fixed :+1: 

I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
