### ISSUE TITLE
Class 'Graphp\\Graph\\Graph' not found

### ISSUE THREAD

**Issue by InterLinked1** [graphp/graphviz#49]
I get a 500 error any time I try using this.

`$graph = new Graphp\Graph\Graph();` is the first line of many examples, which seems clearly wrong. I am requiring `vendor/autoload.php';`

A few examples have:

`use Graphp\GraphViz\GraphViz;`

I've had headaches before where the proper `use` or `require` statements are missing are not provided; how does this library actually get used? I've tried `use Graphp\GraphViz`, `use Graphp\GraphViz\GraphViz`, `use Graphp\Graphp`, etc. to no avail. I'm consistently getting: `PHP Fatal error:  Uncaught Error: Class 'Graphp\\Graph\\Graph' not found in` in the logs.

I installed via composer - have I omitted something here from the process? I'm simply trying to run a simple example provided in this repo.

**Comment by clue** [comment]
Hi @InterLinked1, welcome to GraPHP! :wave: 

Let me self-quote from #45:

> It looks like your referring to the documentation of the current `master` branch which will be released as `v1.0.0` not too far in the future – while you're watching the source code of the `v0.2.x` release branch.
> 
> Please refer to the documentation that comes with your installed version or wait for the `v1.0.0` release which will come with a much better architecture and documentation. In the meantime, you can also install from the `master` branch to get the latest development version :+1:

**Comment by clue** [comment]
I suppose you've installed the latest `graphp/graphviz` release `v0.2.2`. In this case, you can check the documentation here: https://github.com/graphp/graphviz/tree/v0.2.2 (or the `READMEmd` that comes with your installation)

In particular, this means you're also using `clue/graph` release `v0.9.x`. In this case, you'll have to use `Fhaculty\Graph\Graph` instead of `Graphp\Graph\Graph`.

I hope this helps :+1:

**Comment by InterLinked1** [comment]
> I suppose you've installed the latest `graphp/graphviz` release `v0.2.2`. In this case, you can check the documentation here: https://github.com/graphp/graphviz/tree/v0.2.2 (or the `READMEmd` that comes with your installation)

That's what I had, I think, but I deleted that. I am using master now, which I manually downloaded to replace the composer files, so that the examples on the main page will work.

> In particular, this means you're also using `clue/graph` release `v0.9.x`. In this case, you'll have to use `Fhaculty\Graph\Graph` instead of `Graphp\Graph\Graph`.

What I did basically was download the latest src files from the master branch.

I get the same error whether I use Fhaculty or Graph. Here is the code I am trying:

```
require 'common/vendor/autoload.php';
require 'common/vendor/clue/graph/src/GraphViz.php';
#use Graphp\Graph\Graph;
use Fhaculty\Graph\Graph;
use Graphp\GraphViz\GraphViz;

#$graph = new Graphp\Graph\Graph();
$graph = new Fhaculty\Graph\Graph();

$blue = $graph->createVertex();
$blue->setAttribute('id', 'blue');
$blue->setAttribute('graphviz.color', 'blue');

$red = $graph->createVertex();
$red->setAttribute('id', 'red');
$red->setAttribute('graphviz.color', 'red');

$edge = $graph->createEdgeDirected($blue, $red);
$edge = $blue->createEdgeTo($red);
$edge->setAttribute('graphviz.color', 'grey');

$graphviz = new Graphp\GraphViz\GraphViz();
$graphviz->display($graph);
```

And in `common/vendor/clue/graph/src` I have the three files that are currently in the `src` folder in the master branch. Is this correct? Thanks!

**Comment by InterLinked1** [comment]
OK, it seems I accidentally put the GraphViz files into the Graphp folder, which was obviously backwards.

I started over and copied and pasted the code from the master branch into the appropriate files and put them in the right directory.

New code:
```
set_include_path(get_include_path() . ":/var/www/html/interlinked/");
require 'common/vendor/autoload.php';

#use Graphp\Graph\Graph;
use Fhaculty\Graph\Graph;
use Graphp\GraphViz\GraphViz;

#$graph = new Graphp\Graph\Graph();
$graph = new Fhaculty\Graph\Graph();
```
New error:
`PHP Fatal error:  Uncaught Error: Class 'Graphp\\Graph\\Entity' not found in /var/www/html/interlinked/common/vendor/clue/graph/src/Graph.php:5\nStack trace:\n#0 /var/www/html/interlinked/common/vendor/composer/ClassLoader.php(444): include()\n#1 /var/www/html/interlinked/common/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile()\n#2 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#3 /var/www/html/interlinked/insights/graph.php(10): spl_autoload_call()\n#4 {main}\n  thrown in /var/www/html/interlinked/common/vendor/clue/graph/src/Graph.php on line 5`

I checked and there is definitely an `Entity.php` in the directory. Any ideas what could be causing this?

Otherwise, I'm wondering if I should forget about composer and there's a cleaner way of using the code from the respective master branches.

**Comment by clue** [comment]
> What I did basically was download the latest src files from the master branch.

@InterLinked1 It looks like you've ended up with an incomplete and/or incompatible installation. Here's how to install the latest supported version (and all its dependencies):

```bash
$ composer require graphp/graphviz:^0.2.2
```

**Comment by InterLinked1** [comment]
> > What I did basically was download the latest src files from the master branch.
> 
> @InterLinked1 It looks like you've ended up with an incomplete and/or incompatible installation. Here's how to install the latest supported version (and all its dependencies):
> 
> ```shell
> $ composer require graphp/graphviz:^0.2.2
> ```

OK, I purged what I had and then removed the directory and downloaded it again for a fresh copy. These files are timestamped 10/4/2019 and there are three of them in the `src` directory.

Unfortunately, still getting the same error:

`Uncaught Error: Class 'Graphp\\Graph\\Graph' not found in ...graph.php:9`

The problematic line (# 9) is this last one below that is uncommented:

```
require 'common/vendor/autoload.php';

use Graphp\Graph\Graph;
#use Fhaculty\Graph\Graph;
use Graphp\GraphViz\GraphViz;

$graph = new Graphp\Graph\Graph();
#$graph = new Fhaculty\Graph\Graph();
```

In clue\graph\src, I have the 7 files I manually copied and pasted from master branch - is this correct for this setup? At this point, I have the 0.2.2 version of graphviz and the latest version of graphp.

**Comment by clue** [comment]
You really shouldn't have to manually copy/paste any files if you follow the official install instructions. Just delete your manually created files and use Composer to install the latest supported version:

```bash
$ composer require graphp/graphviz:^0.2.2
```
