### ISSUE TITLE
I can get sfdp to repeatably coredump

### ISSUE THREAD

**Issue by dougstarfish** [graphp/graphviz#51]
I have a ~90k line gv file that I'm trying to visualize and layout in graphviz. I have version:
sfdp - graphviz version 2.44.2~dev.20201002.1429 (20201002.1429)

I can repeatable get a coredump. Here is the backtrace (in case it helps)
(gdb) bt
#0  0x00007f017949f994 in compVis (start=0, conf=0x7) at visibility.c:275
#1  visibility (conf=conf@entry=0x9a0b6c0) at visibility.c:304
#2  0x00007f017949b1fe in Pobsopen (obs=obs@entry=0x838be00, n_obs=n_obs@entry=48255) at cvt.c:96
#3  0x00007f017492e8e2 in _spline_edges (g=g@entry=0x2312260, pmargin=pmargin@entry=0x7ffe0b866080, edgetype=edgetype@entry=10)
    at neatosplines.c:582
#4  0x00007f017492ecb9 in splineEdges (g=g@entry=0x2312260, edgefn=edgefn@entry=0x7f017492e2e0 <_spline_edges>, edgetype=10)
    at neatosplines.c:736
#5  0x00007f017492ee4e in spline_edges1 (g=g@entry=0x2312260, edgetype=<optimized out>) at neatosplines.c:749
#6  0x00007f017492f771 in spline_edges0 (g=g@entry=0x2312260, set_aspect=set_aspect@entry=1 '\001') at neatosplines.c:779
#7  0x00007f017492f820 in spline_edges (g=g@entry=0x2312260) at neatosplines.c:817
#8  0x00007f017496cd15 in sfdp_layout (g=0x2312260) at sfdpinit.c:367
#9  0x00007f017a0b817b in gvLayoutJobs (gvc=0x22f3760, g=0x2312260) at gvlayout.c:85
#10 0x0000000000400f5f in main (argc=<optimized out>, argv=<optimized out>) at dot.c:132
(gdb) quit

I can also send a core.
This is on Ubuntu 16.04.1 with a fresh build from github.

**Comment by clue** [comment]
@dougstarfish It looks like you may want to report this upstream in GraphViz: https://gitlab.com/graphviz/graphviz/-/issues

This project here provides a binding between GraPHP and GraphViz, it doesn't implement GraphViz.
