### ISSUE TITLE
Graphp\Graph\Graph() not found!

### ISSUE THREAD

**Issue by tisuchi** [graphp/graphviz#52]
I have installed it on the [Laravel](https://laravel.com) project. I followed [this instruction](https://github.com/graphp/graphviz#install). 

With installation everything successfully, I tried with [sample example](https://github.com/graphp/graphviz#quickstart-examples) that always returns me 
```
Graphp\Graph\Graph
```

What actually I am missing?

**Comment by clue** [comment]
Hi @tisuchi, welcome to GraPHP! :wave: 

Let me self-quote from #45:

> It looks like your referring to the documentation of the current `master` branch which will be released as `v1.0.0` not too far in the future – while you're watching the source code of the `v0.2.x` release branch.
> 
> Please refer to the documentation that comes with your installed version or wait for the `v1.0.0` release which will come with a much better architecture and documentation. In the meantime, you can also install from the `master` branch to get the latest development version :+1:
