### ISSUE TITLE
Get JSON output

### ISSUE THREAD

**Issue by cool-itkfm** [graphp/graphviz#56]
Is it possible to get the JSON output of a graph as seen [here](https://graphviz.org/docs/outputs/json/) with the `-Tjson0` or the `-Tjson` flag?

**Comment by clue** [comment]
@cool-itkfm Good question!

You can indeed specify any format supported by GraphViz with the `setFormat()` method like this:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$graph = new Graphp\Graph\Graph();

$blue = $graph->createVertex();
$blue->setAttribute('id', 'blue');

$red = $graph->createVertex();
$red->setAttribute('id', 'red');

$graph->createEdgeDirected($blue, $red);

$graphviz = new Graphp\GraphViz\GraphViz();
$graphviz->setFormat('json');
$json = $graphviz->createImageData($graph);

echo $json;
```

I hope this helps! :+1: If so, consider supporting this project (for example by contributing to the docs) or by [becoming a sponsor](https://github.com/sponsors/clue).
