### ISSUE TITLE
Add a version which depends on graphp/graph 0.9

### ISSUE THREAD

**Issue by joachim-n** [graphp/graphviz#59]
The releases of this project depend on clue/graph, which AFAICT is outdated and replaced by graphp/graph.

And the HEAD of this project depends on `"graphp/graph": "dev-master#214de45 as 1.0.0"` which is unstable.

It would be really useful to have a v0.2.3 release of this project which had graphp/graph 0.9 as its dependency. Given that 0.2.2 depends on clue/graph ~0.9.0|~0.8.0 I assume this wouldn't involve much more than changing the package dependency in composer.json.

**Comment by SimonFrings** [comment]
@joachim-n thanks for bringing this up :+1: 

As said in graphp/graph#210, we will push the new versions when the time is given.

**Comment by SimonFrings** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
