### ISSUE TITLE
DOT label string '(' in syntax error 

### ISSUE THREAD

**Issue by young-hun-jo** [graphp/graphviz#60]
I want to below string to dot graph. 
```
digraph g {
140515766050320 [label=y: (2, 2) float64, color=orange, style=filled]
140515766047504 [label=Mul, color=lightblue, style=filled, shape=box]
140515766047248 -> 140515766047504
140515766046992 -> 140515766047504
140515766047504 -> 140515766050320
140515766047248 [label=x0: (2, 2) float64, color=orange, style=filled]
140515766046992 [label=x1: (2, 2) float64, color=orange, style=filled]
}
```
but I got this error, `syntax error in line 2 near ':'`. So I remove this string `:` and run below dot code.
```
digraph g {
140515762284624 [label=y(2, 2) float64, color=orange, style=filled]
140515762285072 [label=Mul, color=lightblue, style=filled, shape=box]
140515762285776 -> 140515762285072
140515762283216 -> 140515762285072
140515762285072 -> 140515762284624
140515762285776 [label=x0(2, 2) float64, color=orange, style=filled]
140515762283216 [label=x1(2, 2) float64, color=orange, style=filled]
}
```
but I got this error, `syntax error in line 2 near '('`. 
I want to more string labeling in dot graph node, but dot can't run code including `:` or `(` or `)` in label argument. 
Can I solve this error?

**Comment by young-hun-jo** [comment]
Oh I resolved it. I add double quotation marks `""` to label argument name. 🥲

**Comment by clue** [comment]
@young-hun-jo Happy to hear you've got this sorted out already! It looks like you may have wanted to check and/or report this upstream to the GraphViz community/project :+1: 

This project here provides a binding between GraPHP and GraphViz, it doesn't implement GraphViz.
