### ISSUE TITLE
Unexpected edge duplication / same rank nodes across the subgraphs

### ISSUE THREAD

**Issue by yabeenico** [graphp/graphviz#66]
Unexpected duplicated edges are drawn when its nodes are same rank, across the subgraphs.

```php
// bug.dot
graph g {
    newrank=true // if set false, bug also reproduces. if comment out this line, bug fixes.
    subgraph cluster_1 {a;b}
    subgraph cluster_2 {c}
    {rank=same; a; b; c}
    a -- b -- c // b -- c -- a works correctly
}
```

```
$ dot -V
dot - graphviz version 2.43.0 (0)

$ dot -Tsvg bug.dot >bug.svg
```

![bug](https://github.com/graphp/graphviz/assets/14186615/cbd7be3c-37aa-48e4-8a2e-52b312732071)

**Comment by SimonFrings** [comment]
Hey @yabeenico, you're currently looking at the graphviz project of the GraPHP organisation, this isn't the original GrahViz project. It looks like you may want to check and/or report this upstream to the GraphViz community/project: https://www.graphviz.org/ :+1: 

You can find similar answers in #54 and others
