### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by quantrpeter** [graphp/graphviz#67]
hi
 unable to install, pls help

![image](https://github.com/graphp/graphviz/assets/50471577/ce47893e-7ae8-4d99-bbf9-bea66740f111)

thanks

**Comment by clue** [comment]
@quantrpeter Thank you for reporting! I've just filed #68 to fix the install instructions for the v1 development branch. In a gist, you need to specify both beta versions until the stable tag is released:

```bash
composer require graphp/graphviz:^1@dev graphp/graph:^1@dev
```

I hope this helps! :+1: If so, consider supporting this project (for example by contributing to the docs) or by [becoming a sponsor ❤️](https://github.com/sponsors/clue).
